#!/usr/bin/env bash
set -e
script_dir=$(dirname "$0")

get_cc_prefix() {
    cat $script_dir/gitmoji.txt |\
        fzf \
            --with-nth=3.. \
            --pointer='' \
            --no-unicode \
            --no-scrollbar \
            --no-separator \
            --info=hidden \
            --reverse \
            --height 7 |\
        awk '{print $1": "$3}'
}

args=()
found_flag=false
for var in "$@"
do
    if [ $found_flag = true ]; then
        prefix=$(get_cc_prefix)
        args+=("$prefix $var")
        found_flag=false
    else
        args+=($var)
        if  [[ $var == -* ]] && [[ $var == *m ]]; then
            found_flag=true 
        fi
    fi
done

if [ -z "$prefix" ]; then
    read -p "Commit message: " message
    prefix=$(get_cc_prefix)
    args+=("-m")
    args+=("$prefix $message")
fi
    
git commit "${args[@]}"
